travis:
  secure:
    BINSTAR_TOKEN: GcPx2gqXTpaJ1GTnK6mSUVQsO9pcVECE41gAUD8IXGfWmMsfAaFZ3GQbhwnJony+sfxdT25ln+pWRO4kLU6yRFIZqChv1EQVwG/bLat+/csSTy9XI+xNKjrv0jl7FrpnBkxky6/D0lTMdeDi0cqjL05g8Kvwc3W3wqN1zAtFAxicW2yI9/nlb/cIICyw6KYfE75VvQYOIBSUG3YUXJOiAvOzPnvVbTkP8GzGBXojOxHr3xKuz4ZBGl36QuYGaRLxIsDrhM/ro6AFA51BzFIoi1Hobgl6KkOoTVqa8TVLtwZgiP/LHC1/L5kq4pkt4MECNEtIXPZ7DKiuW3S5ELzv0NMNC3tRApTaNPh2tHodwGeX2Nk4YfP6kCGU4J8JLSoW+oH013E1lzkNQayJzuLaikuKXBDzKIt+KpWR8A+ByErHwXUKDQTy6URviIwba1gyCF9N1zHDz0hQTq0DOsSF84X4dQymawrgtBtIn3fzH7uGsCG3vZF73Ph76b0cRBNYF58c+PZpAi7EJfIe0on5YK/vm6VSBeIv61ibIzBfHbOyLwfTm7NFwVFCD+Vehk3ezC6GKHIjqvroZOByFFKtwxSUgmttOY3G0p591E+wiyyScjrKJQTNnQGrrbOqviml5yxoH1/2mCf1A8+1Vf3SRnh1MSBfQCHzYO9wLSMIVHQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
